DROP TABLE IF EXISTS correos;
CREATE TABLE IF NOT EXISTS correos (
     id INT AUTO_INCREMENT PRIMARY KEY,
     asunto VARCHAR(255) NOT NULL,
    mensaje TEXT NOT NULL,
    fecha_envio DATETIME DEFAULT CURRENT_TIMESTAMP,
    estado ENUM('PENDIENTE', 'ENVIADO', 'FALLIDO') DEFAULT 'ENVIADO'
);
